config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :sessions
  resources :likes
  resources :ingredients

  resources :publishes do
    member do
      post 'add_like'
      post 'add_dislike'
      post 'delete_vote'
      post 'api_add_like'
      post 'api_add_dislike'
      post 'api_create_publish'
    end
  end

  # Drink API likes and dislikes
  get "publishes/:id/api_drink_add_like" => "publishes#api_drink_add_like"
  get "publishes/:id/api_drink_add_dislike" => "publishes#api_drink_add_dislike"

  # Ingredient Search
  get 'ingred_search' => 'ingred_search#show'
  match  '/ingreds/results', to: 'ingred_search#pagehandler', as: 'ingred_page', via: [:get, :post]
  get "/ingreds/search", to: 'ingred_search#ingredstartsearch', as: 'ingred_startsearch'

  # Sessions
  get "sign_up" => "users#new", :as => "sign_up"
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"

  # Edit profile
  get "edit_bio" => "edit_profile#edit_bio", :as => "edit_bio"
  get 'edit_profile/edit_bio'
  get 'edit_profile/edit_email_profile'

  # Password configuration
  get "change_password" => "change_password#change", :as => "change_password"
  post "change_password" => "change_password#change", :as => "change_password/success"
  get "reset_password" => "change_password#reset", :as => "reset_password"
  post "reset_password" => "change_password#reset", :as => "reset_password/success"

  # Drinks
  get "/drinks/searched" => 'drinks#drinksearch', as: 'drink_search'
  get "/drinks/show", to: 'drinks#show', as: "drink_show"
  match "/drinks/search", to: 'drinks#drinkresults', as: 'drink_results', via: [:get, :post]

  # Errors
  get "/404", to: 'errors#not_found', as: "error_404"

  # Other pages
  root 'welcome#index'
  get "just_logged_in", to: 'welcome#just_logged_in', as: "just_logged_in"
  get "about_us", to: 'welcome#about_us', as: "about_us"

  get 'liquorsearch' => 'mapsearch#liquorsearch'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
def show
  if @drink == nil
    @drink = params[:drink]
  end
end

def drinksearch
  if params[:searchBarDrink] == ''
    redirect_to root_url
  end
  params[:searchBarDrink].gsub!("'", '\%27')
  @published = Publish.all
  @publishresults = Array.new
  # Search through published drinks for matches
  @published.each do |drink|
    if drink.id > 0
      if drink.name.downcase.include? params[:searchBarDrink].downcase
        @publishresults.push(drink)
      end
    end
  end
  # puts params[:searchBarDrink]
  url = "http://www.thecocktaildb.com/api/json/v1/1/search.php?s=#{params[:searchBarDrink]}"
  uri = URI(url)
  response = Net::HTTP.get(uri)
  parsed = JSON.parse(response)
  if parsed['drinks'] == nil && @publishresults.count == 0
    redirect_to root_url
    flash.alert = "No matched drinks found"
  elsif parsed['drinks'] == nil || parsed['drinks'][0]['strDrink'] != params[:searchBarDrink]
      @APIresults = parsed['drinks']
      render "drinkresults"
  else
      @drink = parsed['drinks'][0]
      render "show"
  end
end

def drinkresults
  # @results = params[:results]
  if params[:page] == nil
    @page = 1
  else
    @page = params[:page]
  end
  @pagerange = @results[(@page.to_i-1)*10..[@page.to_i*10-1, @results.size-1].min]
end

end

app/views/drinks/drinkresults.html.erb
<!-- <div>
  <%= button_to("Prev", drink_results_path(:page => @page.to_i-1, :results => @results), :class => 'pageLinks') %>
  <span class="pageLinks">Page <%= @page.to_i %></span>
  <%= button_to("Next", drink_results_path(:page => @page.to_i+1, :results => @results), :class => 'pageLinks') %>
</div>
This isn't<body style="height:90%;width:100%; ">-->
<%= flash_message %>
<body style="background-color:black;">
<div class="jumbotron" style="background-image: url('/assets/signupbg.jpg'); min-height: 100%; min-height: 100vh;">
<div class="container-fluid" style="margin-left:20px;">
<div class='searchResults'>
  <p><img alt="Image" src="/assets/drinkresult.png" > </p>
  <br></br>
  <% if @publishresults.count != 0 %>
    <p style='clear:both'>User-created Drinks</p>
    <% @publishresults.each do |drink| %>
      <div style="clear:both">
        <div class="drinkImage">
          <%= image_tag( drink['image'] ? "#{drink.image.thumb.url}" : "no-image.jpg", size: "150x150", alt: "") %>
        </div>
        <%= link_to("#{drink["name"]}", drink, :class => 'drinkName searchResultsName') %>
      </div>
    <% end %>
  <% end %>
  <% if @APIresults != nil %>
    <p style='clear:both'>Pre-existing Drinks</p>
    <% @APIresults.each do |drink| %>
      <div style="clear:both">
        <div class="drinkImage">
          <%= image_tag( drink['strDrinkThumb'] ? "#{drink['strDrinkThumb']}" : "no-image.jpg", size: "150x150", alt: "") %>
        </div>
        <%= link_to("#{drink["strDrink"]}", drink_show_path(:drink => drink), :class => 'drinkName searchResultsName') %>
      </div>
    <% end %>
  <% end %>
</div>
</div>
</div>
</body>

app/views/drinks/show.html.erb
<body style="height:100%;width:100%;background-color:black; ">
<%= flash_message %>

<% @ApiDrink = drink_in_database(@drink['strDrink']) %>

<div class="jumbotron vertical-centers" style="background-image: url('/assets/publishbg.jpg'); min-height: 100%; min-height: 100vh;">

<div class="container-fluid" style="margin-left:20px;">
<div class="drinkImage">
  <%= image_tag( @drink['strDrinkThumb'] && @drink['strDrinkThumb'] != "" ? "#{@drink['strDrinkThumb']}" : 'no-image.jpg', size: "200x200", alt: "") %>

</div>
<div class="drinkDetails" style="margin-left:10px;">
  <h1 class="drinkName"><%= @drink['strDrink']%></h1>
  <ul class="ingredients">
    <%= for i in 1..15 do %>
      <% if @drink["strIngredient#{i}"] == "" then %>
        <% break %>
      <% end %>
      <li style="font-size:18px;"><%= @drink["strMeasure#{i}"] %><%= @drink["strIngredient#{i}"]%></li>
    <% end %>
  </ul>
</div>

<strong>
  <% if @ApiDrink == nil %>
      <!--Likes: 0<br>
      Dislikes: 0-->
  <% else %>
      Likes: <%= count_like(@ApiDrink) %><br>
      Dislikes: <%= count_dislike(@ApiDrink) %>
  <% end %>
</strong>

  <p class="instructions"><%= @drink['strInstructions'] %></p>


<% if @ApiDrink == nil %>
  <!--
  <% if current_user %>
    <%= link_to 'Like', root_url %> |
    <%= link_to 'Dislike', root_url %>

  <% else %>
    <%= link_to 'Like', sign_up_url %> |
    <%= link_to 'Dislike', sign_up_url %>
  <% end %>
  -->
<% else %>

  <% if current_user %>

    <% liked = false %>
    <% disliked = false %>
    <% current_user.likes.each do |l| %>
      <% if l.publish_id == @ApiDrink.id %>
        <% if l.islike %>
          <% liked = true %>
        <% else %>
          <% disliked = true %>
        <% end %>
        <% break %>
      <% end %>
    <% end %>

    <% if liked %>
      <%= link_to 'Un-like', delete_vote_publish_path(@ApiDrink), method: :post %> |
    <% elsif disliked %>
      <%= link_to 'Un-dislike', delete_vote_publish_path(@ApiDrink), method: :post %> |
    <% else %>
      <%= link_to 'Like', add_like_publish_path(@ApiDrink), method: :post %> |
      <%= link_to 'Dislike', add_dislike_publish_path(@ApiDrink), method: :post  %>
    <% end %>

  <% else %>
    <%= link_to 'Like', sign_up_url, method: :get %> |
    <%= link_to 'Dislike', sign_up_url, method: :get %>
  <% end %>

<% end %>



</div>
</div>
</body