config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :sessions
  resources :likes
  resources :ingredients

  resources :publishes do
    member do
      post 'add_like'
      post 'add_dislike'
      post 'delete_vote'
      post 'api_add_like'
      post 'api_add_dislike'
      post 'api_create_publish'
    end
  end

  # Drink API likes and dislikes
  get "publishes/:id/api_drink_add_like" => "publishes#api_drink_add_like"
  get "publishes/:id/api_drink_add_dislike" => "publishes#api_drink_add_dislike"

  # Ingredient Search
  get 'ingred_search' => 'ingred_search#show'
  match  '/ingreds/results', to: 'ingred_search#pagehandler', as: 'ingred_page', via: [:get, :post]
  get "/ingreds/search", to: 'ingred_search#ingredstartsearch', as: 'ingred_startsearch'

  # Sessions
  get "sign_up" => "users#new", :as => "sign_up"
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"

  # Edit profile
  get "edit_bio" => "edit_profile#edit_bio", :as => "edit_bio"
  get 'edit_profile/edit_bio'
  get 'edit_profile/edit_email_profile'

  # Password configuration
  get "change_password" => "change_password#change", :as => "change_password"
  post "change_password" => "change_password#change", :as => "change_password/success"
  get "reset_password" => "change_password#reset", :as => "reset_password"
  post "reset_password" => "change_password#reset", :as => "reset_password/success"

  # Drinks
  get "/drinks/searched" => 'drinks#drinksearch', as: 'drink_search'
  get "/drinks/show", to: 'drinks#show', as: "drink_show"
  match "/drinks/search", to: 'drinks#drinkresults', as: 'drink_results', via: [:get, :post]

  # Errors
  get "/404", to: 'errors#not_found', as: "error_404"

  # Other pages
  root 'welcome#index'
  get "just_logged_in", to: 'welcome#just_logged_in', as: "just_logged_in"
  get "about_us", to: 'welcome#about_us', as: "about_us"

  get 'liquorsearch' => 'mapsearch#liquorsearch'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :publishes
  has_many :likes, dependent: :destroy

  attr_accessor :Password

  before_save :CreateHashedPassword
  before_update :check_password

  EMAIL = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :Username, :presence => true, :uniqueness => true, :length => 3..20
  validates :Email, :presence => true, :uniqueness => true, :format => EMAIL
  validates :Password, :presence => true, :confirmation => true, :length => 6..20, on: :create

  def CreateHashedPassword
    return unless self.Password.present?
    self.passwordsalt = BCrypt::Engine.generate_salt
    self.hashedpassword = BCrypt::Engine.hash_secret(self.Password, passwordsalt)
  end

  def self.authenticate(email_or_username, password)
    user = EMAIL.match(email_or_username) ? (find_by Email: email_or_username) : (find_by Username: email_or_username)
    if user && user.hashedpassword == BCrypt::Engine.hash_secret(password, user.passwordsalt)
      user
    else
      nil
    end
  end

  def is_liked()
    if Like.where(:publish, :user_id => self.id).present?
      Like.where(:publish, :user_id => self.id).last.islike==true
    end
  end

  def is_disliked()
    if Like.where(:publish, :user_id => self.id).present?
      Like.where(:publish, :user_id => self.id).last.islike==false
    end
  end
  
private
  def check_password
    is_ok = self.Password.nil? || self.Password.empty? || self.Password.length >= 6

      self.errors[:Password] << "Password is too short (minimum is 6 characters)" unless is_ok
      is_ok
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :check_admin, only: :index
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    if current_user
      redirect_to root_url
      return
    end
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    #redirect_to edit_user_path(current_user) if @user.id != current_user.id
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.Isadmin = false if @user.Isadmin == ''
    if @user.save
      if @user.Isadmin
        redirect_to users_url
      else
        redirect_to just_logged_in_url, :notice => "Signed up!"
      end
      session[:user_id] = @user.id
    else
      render "new"
    end
  end
=begin
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
=end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if current_user.id == @user.id
      @user.destroy
      respond_to do |format|
        format.html { redirect_to log_out_path, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      @user.destroy
      respond_to do |format|
        format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:Username, :Password, :Password_confirmation, :Email, :Biography, :Isadmin)
    end



    def check_admin
      redirect_to(root_url) unless current_user && current_user.Isadmin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li style="color:white"><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <br></br>
    <p class="smalltag"><%= f.label :Username %></p>
    <%= f.text_field :Username,:id => "inputfield" %>
  </div>

  <div class="field">
    <br></br>
    <p class="smalltag"><%= f.label :Email %></p>
    <%= f.text_field :Email,:id => "inputfield" %>
  </div>

  <div class="field">
    <br></br>
    <p class="smalltag"><%= f.label :Biography%></p>
    <p style="font-size:15px;"><%= f.text_area :Biography, size: "15x5" %></p>
  </div>

  <% if current_user && current_user.Isadmin? %>
    <div class="field">
      <p class="smalltag"><%= f.label :Isadmin %></p>
      <%= f.check_box :Isadmin %>
    </div>
  <div class="field">
    <p class="smalltag">For admin user only, change password without confirmation</p>
    <p class="smalltag"><%= f.label :Password %></p>
    <%= f.password_field :Password,:id => "inputfield"%>
  </div>

    <!--<div class="field">
    <p class="smalltag"><%= f.label :Password_confirmation %></p>
    <%= f.password_field :Password_confirmation,:id => "inputfield" %>
  </div>-->
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>


<% end %>

app/views/users/edit.html.erb
<body style="height:100%;width:100%; background-color:black" >
<div class="jumbotron vertical-centers" style="background-image: url('/assets/publishbg.jpg'); min-height: 100%; min-height: 100vh;">
<div class="container-fluid" style="margin-left:20px;">
<p><img alt="Image" src="/assets/editprofile.png" /> </p>
<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

<% if current_user %>
  <% if !current_user.Isadmin && current_user.id == @user.id %>
    <br></br><br></br>
    <%= link_to 'Delete Your Account', @user, method: :delete, data: { confirm: 'Are you sure you want to deactivate? This action cannot be undone.' } %>
  <% end %>
<% end %>
</div>
</div>
</body>

app/views/users/index.html.erb
<body style="height:100%;width:100%; background-color:black">
<div class="jumbotron" style="background-image: url('assets/signupbg.jpg'); min-height: 100%; min-height: 100vh;">
    <div class="container-fluid">
  <h1><img alt="Image" src="/assets/admin.png" /> </h1>
  <br></br>

  <table>
    <thead>
      <tr>
        <th class="rowhead">Username</th>
        <th class="rowhead">Email</th>
        <th class="rowhead">Isadmin</th>
        <th class="rowhead" colspan="3">Options</th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td class="column"><%= user.Username %></td>
          <td class="column"><%= user.Email %></td>
          <td class="column"><%= user.Isadmin %></td>
          <td class="column"><%= link_to 'Show', user %></td>
          <% if user.Username != 'admin' %>
            <td class="column"><%= link_to 'Edit', edit_user_path(user) %></td>
          <% end %>
          <% if user.Username != 'admin' %>
            <td class="column"><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Make new User', new_user_path %>
</div>
</div>
</body>

app/views/users/new.html.erb
<head>
  <title>Sign Up</title>
</head>
<body style="height:100%;width:100%; background-color:black">
<div class="jumbotron vertical-centers" style="background-image: url('assets/signupbg.jpg'); min-height: 100%; min-height: 100vh; display: flex;  align-items: center;">
    <div class="container-fluid">
      <%= form_for(@user) do |f| %>
      <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
          <% @user.errors.full_messages.each do |message| %>
          <li style="color:white"><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>
<div class="container-fluid">
  <p><img alt="Image" src="/assets/signup.png" > </p>
  <div class="field">
    <p class = "smalltag">Username:</p>
    <%= f.text_field :Username %>
  </div>

  <div class="field">
      <p class = "smalltag">Email:</p>
    <%= f.text_field :Email %>
  </div>

  <div class="field">
    <p class = "smalltag">Password:</p>
    <%= f.password_field :Password %>
  </div>

  <div class="field">
      <p class = "smalltag">Confirm Password:</p>
    <%= f.password_field :Password_confirmation %>
  </div>

  <% if current_user %>
    <% if current_user.Isadmin == true %>
    <div class="field">
      <%= f.label :Isadmin %>
      <%= f.check_box :Isadmin %>
    </div>

    <% end %>
  <% end %>

    <div class="actions">
      <%= f.submit %>|
      <%= link_to "Have an Account? Sign In!", log_in_path %>
    </div>
  <% end %>
</div>
  </div>
</div>
</body>

app/views/users/show.html.erb
<body style="background-color:black;">
<div class="jumbotron" style="background-image: url('/assets/profilebg.jpg'); min-height: 100%; min-height: 100vh; ">

<div class="container-fluid" style="margin-left:20px;">
  <p><img alt="Image" src="/assets/profiletitle.png" > </p>
  <div id="userinfodisplay">
      <p class="smalltag">Username:</p>
      <p style="font-size:15px;"><%= @user.Username %></p>
    <br>
      <p class="smalltag">Email:</p >
      <p style="font-size:15px;"><%= @user.Email %></p>
    <br>
      <p class="smalltag">Biography:</p>
    <div class="biographydisplay"><p style="color:white; font-size: 15px; width: 300px;height: 80px;overflow:auto; word-wrap:break-word; word-break:normal;">  <%= @user.Biography %></p></div>
  <div>
    <% if current_user && @user.id == current_user.id %>
      <p style="color:whte;font-size:15px"><%= link_to 'Edit Profile', edit_user_path(@user),{:style=>'color:#FFFFFF;'} %> |
      <%= link_to 'Change Password', change_password_url, {:style=>'color:#FFFFFF;'} %></p>
    <% elsif current_user %>
    <% end %>
<br>

  </div>
</div>

<br></br>
<div id="container-fluid">
  <br>
  <p><%= "Recipes made by " + @user.Username%></p>
    <% if @user.publishes.size > 0 %>
    <table id="publishes">
      <% @user.publishes.each do |d| %>
        <tr>
          <td id="drinkrow"><%= link_to d.name, d,{:style=>'color:#FFFFFF;'} %></td>

        </tr>
      <% end %>
    </table>
    <% else %>
      <p>This user did not publish any recipes</p>
    <% end %>
</div>

<br></br>
<div id="container-fluid">
<p><p><%= "Recipes liked by " + @user.Username%></p</p>
<div>
  <table id="Likes">
  <% @user.likes.where(islike:true).each do |l| %>
    <tr>
    <% @tempPublishObj = Publish.find_by(:id => l.publish_id) %>
    <td id="drinkrow"><%= link_to @tempPublishObj.name, @tempPublishObj %></td>

    <% if @user == current_user %>
      <td id="drinkrow"><a style="color:white;"<%= link_to 'Un-like', l, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
    </tr>
  <% end %>
  </table>
</div>

<% if @user.likes.where(islike:true).count == 0 %>
  <p>This user has no likes</p>
<% end %>

</div>
</div>
</body>