config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :sessions
  resources :likes
  resources :ingredients

  resources :publishes do
    member do
      post 'add_like'
      post 'add_dislike'
      post 'delete_vote'
      post 'api_add_like'
      post 'api_add_dislike'
      post 'api_create_publish'
    end
  end

  # Drink API likes and dislikes
  get "publishes/:id/api_drink_add_like" => "publishes#api_drink_add_like"
  get "publishes/:id/api_drink_add_dislike" => "publishes#api_drink_add_dislike"

  # Ingredient Search
  get 'ingred_search' => 'ingred_search#show'
  match  '/ingreds/results', to: 'ingred_search#pagehandler', as: 'ingred_page', via: [:get, :post]
  get "/ingreds/search", to: 'ingred_search#ingredstartsearch', as: 'ingred_startsearch'

  # Sessions
  get "sign_up" => "users#new", :as => "sign_up"
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"

  # Edit profile
  get "edit_bio" => "edit_profile#edit_bio", :as => "edit_bio"
  get 'edit_profile/edit_bio'
  get 'edit_profile/edit_email_profile'

  # Password configuration
  get "change_password" => "change_password#change", :as => "change_password"
  post "change_password" => "change_password#change", :as => "change_password/success"
  get "reset_password" => "change_password#reset", :as => "reset_password"
  post "reset_password" => "change_password#reset", :as => "reset_password/success"

  # Drinks
  get "/drinks/searched" => 'drinks#drinksearch', as: 'drink_search'
  get "/drinks/show", to: 'drinks#show', as: "drink_show"
  match "/drinks/search", to: 'drinks#drinkresults', as: 'drink_results', via: [:get, :post]

  # Errors
  get "/404", to: 'errors#not_found', as: "error_404"

  # Other pages
  root 'welcome#index'
  get "just_logged_in", to: 'welcome#just_logged_in', as: "just_logged_in"
  get "about_us", to: 'welcome#about_us', as: "about_us"

  get 'liquorsearch' => 'mapsearch#liquorsearch'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/publish.rb
class Publish < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :ingredients, dependent: :destroy
  accepts_nested_attributes_for :ingredients

  validates :name, :instructions, :presence => true, :uniqueness => true
  mount_uploader :image, ImageUploader

  validates_processing_of :image
  validate :image_size_validation

  def add_like(user)
    self.create_vote(user,true)
  end

  def add_dislike(user)
    self.create_vote(user,false)
  end

  def create_vote(user,vote)
    new_vote = Like.new
    new_vote.islike = vote
    user.likes << new_vote
    self.likes << new_vote
    new_vote.save
  end

  def delete_vote(user)
    self.delete_the_vote
  end

  private
    def image_size_validation
      errors[:image] << "should be less than 2.5MB" if image.size > 2.5.megabytes
    end
end

app/controllers/publishes_controller.rb
class PublishesController < ApplicationController
  before_action :set_publish, only: [:show, :edit, :update, :destroy]

  # GET /publishes
  # GET /publishes.json
  def index
    @publishes = Publish.all
  end

  # GET /publishes/1
  # GET /publishes/1.json
  def show
  end

  # GET /publishes/new
  def new
    @publish = Publish.new
    15.times { @publish.ingredients.build }
  end

  # GET /publishes/1/edit
  def edit
    @publish = Publish.find(params[:id])
    if @publish.user_id != current_user.id
      redirect_to current_user
    end
    remaining_blank_inputs = 15 - @publish.ingredients.size
    remaining_blank_inputs.times { @publish.ingredients.build }
  end

  def destroy_invalid_inputs
    @publish.ingredients.each do |i|
      i.destroy unless i.name=~/[A-Za-z]/
    end
  end

  def add_like
    create_vote(true)
  end

  def add_dislike
    create_vote(false)
  end

  def create_vote(vote)
    @publish = Publish.find(params[:id])
    new_vote = Like.new
    new_vote.islike = vote
    current_user.likes << new_vote
    @publish.likes << new_vote
    new_vote.save
    redirect_to(@publish)
  end

  def delete_vote
    @publish = Publish.find(params[:id])
    @publish.likes.where(:publish_id => @publish.id, :user_id => current_user.id).destroy_all
    respond_to do |format|
      format.html { redirect_to publish_path(@publish) }
      format.xml  { head :ok }
    end
  end

  def api_add_like(api_drink)
    @publish = Publish.new
    @publish = create_publish(api_drink)
    @publish.save
    return add_like_publish_path(@publish)
  end

  def api_add_dislike(api_drink)
    @publish = Publish.new
    @publish = create_publish(api_drink)
    @publish.save
    return add_dislike_publish_path(@publish)
  end

  def api_create_publish(api_drink)
    @publish.id = Publish.all.size
    @publish.image = api_drink['strDrinkThumb']
    @publish.name = api_drink['strDrink']
    for i in 1..15 do
      next if api_drink["strIngredient#{i}"] == ""
      @ingredient = Ingredient.new
      @ingredient.name = api_drink["strMeasure#{i}"] + api_drink["strIngredient#{i}"]
      @publish.ingredients << @ingredient
      @ingredient.save
    end
    @publish.instructions = api_drink['strInstructions']
    return @publish
  end

  # POST /publishes
  # POST /publishes.json
  def create
    @publish = Publish.new(publish_params)
    begin
      unless current_user.nil?
        @publish.user_id = current_user.id
      end
    rescue ActionView::Template::Error
    end
    destroy_invalid_inputs
    if @publish.save
      redirect_to @publish
      flash[:success] = "Drink successfully created."
    else
      render 'new'
    end
=begin
    respond_to do |format|
      if @publish.save
        format.html { redirect_to @publish, notice: 'Publish was successfully created.' }
        format.json { render :show, status: :created, location: @publish }
      else
        format.html { render :new }
        format.json { render json: @publish.errors, status: :unprocessable_entity }
      end
    end
=end
  end

  # PATCH/PUT /publishes/1
  # PATCH/PUT /publishes/1.json
  def update
    respond_to do |format|
      if @publish.update(publish_params)
        destroy_invalid_inputs
        format.html { redirect_to @publish, notice: 'Drink updated' }
        format.json { render :show, status: :ok, location: @publish }
      else
        format.html { render :edit }
        format.json { render json: @publish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publishes/1
  # DELETE /publishes/1.json
  def destroy
    @publish.destroy
    respond_to do |format|
      format.html { redirect_to current_user, notice: 'Drink was successfully deleted' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publish
      @publish = Publish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publish_params
      params.require(:publish).permit(:name, :image, :instructions, :user_id, :drink_id, :remove_image, ingredients_attributes: [:id, :name])
    end
end

app/helpers/publishes_helper.rb
module PublishesHelper
end

app/views/publishes/_form.html.erb
<%= form_for(publish) do |f| %>
  <% if publish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(publish.errors.count, "error") %> prohibited this publish from being saved:</h2>

      <ul>
      <% publish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <p class="smalltag"><%= f.label :user_id %>
    <%= ": " + current_user.Username %></p>
  </div>

  <div class="field">
    <p class="smalltag"><%= f.label :Drink_Name %></p>
    <%= f.text_field :name, :id => "inputfield" %>
  </div>

  <div class="field">
    <p class="smalltag"><%= f.label :Upload_Image %><%= f.file_field :image %></p>
    <% if f.object.image? %>
      <%= image_tag f.object.image.thumb.url %>
    <p><%= f.label :remove_image %></p>
    <p> <%= f.check_box :remove_image %></p>
    <% end %>
  </div>

  <br></br>
  <div>
    <p class="smalltag"><%= f.label :Ingredients %></p>
    <%= f.fields_for :ingredients do |builder| %>
      <%= builder.text_field :name, :id=>"inputfield" %><br/>
    <% end %>
  </div>
  <br></br>
<p class="smalltag"><%= f.label :instructions %></p>
  <div>
    <p style="color:white; font-size: 15px;">
    <%= f.text_area :instructions,size:  "20x10"%></p>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/publishes/edit.html.erb
  <body style="height:100%;width:100%; background-color:black" >
<div class="jumbotron vertical-centers" style="background-image: url('/assets/publishbg.jpg'); min-height: 100%; min-height: 100vh;">
<div class="container-fluid" style="margin-left:20px;">
  <p><img alt="Image" src="/assets/edittitle.png" > </p>
  <%= render 'form', publish: @publish %>
  <%= link_to 'Back', @publish,{:style=>'color:#FFFFFF;'} %>
</div>
</div>
</body>

app/views/publishes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Publishes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th>Ingredients</th>
      <th>Instructions</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @publishes.each do |publish| %>
      <tr>
        <td><%= link_to publish.name, publish %></td>
        <td><%= image_tag (publish.image.blank? ? "no-image.jpg" : publish.image.thumb.url), size: "200x200", alt: "Image not found." %></td>
        <td><%= publish.ingredients %></td>
        <td><%= publish.instructions %></td>
        <td><%= link_to 'Show', publish %></td>
        <!--<td><%= link_to 'Edit', edit_publish_path(publish) %></td>
        <td><%= link_to 'Destroy', publish, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user %>
  <%= link_to 'New Publish', new_publish_path %>
<% end %>

app/views/publishes/new.html.erb
  <body style="height:100%;width:100%; background-color:black" >
<div class="jumbotron vertical-centers" style="background-image: url('/assets/publishbg.jpg'); min-height: 100%; min-height: 100vh;">
<div class="container-fluid" style="margin-left:20px;">
  <p><img alt="Image" src="/assets/publishtitle.png" > </p>
  <%= render 'form', publish: @publish %>
  <%= link_to 'Back', publishes_path,{:style=>'color:#FFFFFF;'} %>
</div>
</div>
</body>

app/views/publishes/show.html.erb
<body style="height:100%;width:100%;background-color:black; ">
<div class="jumbotron vertical-centers" style="background-image: url('/assets/publishbg.jpg'); min-height: 100%; min-height: 100vh;">
<div class="container-fluid" style="margin-left:20px;">

<div class="drinkImage">
  <%= image_tag (@publish.image.blank? ? "no-image.jpg" : @publish.image.thumb.url), size: "200x200", alt: "Image not found." %>
</div>
<div class="drinkDetails">
    <h1 class="drinkName"><%= @publish.name %></h1>
    <p>
        <% if @publish.user != nil %>
          Made by: <%= link_to @publish.user.Username, @publish.user %>
        <% end %>
    </p>

<ul class="ingredients", style="font-size:18px;">
  <% @publish.ingredients.each do |i| %>
    <li style="font-size:18px;"><%= i.name %></li>
  <% end %>
  </strong>
</p>

    <br></br>
    <strong>
      Likes: <%= count_like(@publish) %><br>
      Dislikes: <%= count_dislike(@publish) %>
    </strong>
  </li>

</ul>
<p class="instructions"><%= @publish.instructions %></p>


<% if current_user %>

  <% liked = false %>
  <% disliked = false %>
  <% current_user.likes.each do |l| %>
    <% if l.publish_id == @publish.id %>
      <% if l.islike %>
        <% liked = true %>
      <% else %>
        <% disliked = true %>
      <% end %>
      <% break %>
    <% end %>
  <% end %>

  <% if liked %>
    <%= link_to 'Un-like', delete_vote_publish_path(@publish), method: :post %> |
  <% elsif disliked %>
    <%= link_to 'Un-dislike', delete_vote_publish_path(@publish), method: :post %> |
  <% elsif @publish.user==nil || @publish.user.id != current_user.id %>
    <%= link_to 'Like', add_like_publish_path(@publish), method: :post %> |
    <%= link_to 'Dislike', add_dislike_publish_path(@publish), method: :post  %>
  <% end %>

<% else %>
  <%= link_to 'Like', sign_up_url %> |
  <%= link_to 'Dislike', sign_up_url %>

<% end %>

<br></br>
<% if current_user %>
  <% if @publish.user_id == current_user.id || current_user.Isadmin %>
    <td><%= link_to 'Edit', edit_publish_path(@publish),{:style=>'color:#FFFFFF;'} %></td><br>
    <td><%= link_to 'Delete', @publish, method: :delete, data: { confirm: 'Are you sure?'} %></td>
  <% end %>
<% end %>

</div>
</div>
</div>
</body>