config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :sessions
  resources :likes
  resources :ingredients

  resources :publishes do
    member do
      post 'add_like'
      post 'add_dislike'
      post 'delete_vote'
      post 'api_add_like'
      post 'api_add_dislike'
      post 'api_create_publish'
    end
  end

  # Drink API likes and dislikes
  get "publishes/:id/api_drink_add_like" => "publishes#api_drink_add_like"
  get "publishes/:id/api_drink_add_dislike" => "publishes#api_drink_add_dislike"

  # Ingredient Search
  get 'ingred_search' => 'ingred_search#show'
  match  '/ingreds/results', to: 'ingred_search#pagehandler', as: 'ingred_page', via: [:get, :post]
  get "/ingreds/search", to: 'ingred_search#ingredstartsearch', as: 'ingred_startsearch'

  # Sessions
  get "sign_up" => "users#new", :as => "sign_up"
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"

  # Edit profile
  get "edit_bio" => "edit_profile#edit_bio", :as => "edit_bio"
  get 'edit_profile/edit_bio'
  get 'edit_profile/edit_email_profile'

  # Password configuration
  get "change_password" => "change_password#change", :as => "change_password"
  post "change_password" => "change_password#change", :as => "change_password/success"
  get "reset_password" => "change_password#reset", :as => "reset_password"
  post "reset_password" => "change_password#reset", :as => "reset_password/success"

  # Drinks
  get "/drinks/searched" => 'drinks#drinksearch', as: 'drink_search'
  get "/drinks/show", to: 'drinks#show', as: "drink_show"
  match "/drinks/search", to: 'drinks#drinkresults', as: 'drink_results', via: [:get, :post]

  # Errors
  get "/404", to: 'errors#not_found', as: "error_404"

  # Other pages
  root 'welcome#index'
  get "just_logged_in", to: 'welcome#just_logged_in', as: "just_logged_in"
  get "about_us", to: 'welcome#about_us', as: "about_us"

  get 'liquorsearch' => 'mapsearch#liquorsearch'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Mixbook</title>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    No need to include jquery again. It's already here.-->
 <!-- CSS reset -->

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
      <link rel="stylesheet" href="assets/stylesheets/style.css">
      <link rel="stylesheet" href="assets/stylesheets/autocomplete.css">

  </head>

  <body class>
    <nav class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid" >

        <div class="navbar-brand" style="padding-top:2%;"><%=link_to image_tag("Logo1.png"), root_url,:method => 'get'%></div>
        <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
      </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li class="hidden">
                    <a href="#page-top"></a>
                </li>
                <% if current_user %>
                  <% if current_user.Isadmin == true %>
                    <li><a class="active"> <%= link_to "Users", users_url , :method => 'get'%></a></li>
                  <% end %>
                <% end %>
                <% if current_user %>
                  <li><a class="active"><%= link_to 'Profile', current_user, :method => 'get'%></a></li>
                  <li><a class="active"> <%= link_to 'Publish', new_publish_path, :method => 'get'%></a></li>
                <% else %>
                  <li><a class="active"> <%= link_to 'Profile', sign_up_url, :method => 'get'%></a></li>
                  <li><a class="active"> <%= link_to 'Publish', sign_up_url, :method => 'get'%></a></li>
                <% end %>

                <li>
                    <a class="active"><%=link_to'About us', about_us_url, :method => 'get'%></a>
                </li>
                <% if current_user %>
                  <li><a class="active" style="padding-top:45px;"> Logged in as <%= current_user.Username %></a></li>
                  <li><a class="active"> <%= link_to "Log out", log_out_path, :method => 'get' %></a></li>
                <% else %>
                  <li><a class="active"> <%= link_to "Sign up", sign_up_path, :method => 'get' %></a></li>
                  <li><a class="active"> <%= link_to "Log in", log_in_path, :method => 'get' %></a></li>
                <% end %>

                <li id="searchIngredfield" style=" vertical-align:middle; line-height:110px; padding-left:40px; padding-right:40px;">

                      <%= form_tag(ingred_startsearch_path, :method => 'get', :id =>'form_id') do %>
                          <%= link_to "Ingredient Search ", ingred_startsearch_path, :onclick => "$('#form_id').submit()", :style => "color:#999"%>
                      <% end %>
                </li>

                <li id="searchDrinkfield" class="searchbar" style="padding-top:35px;">
                  <%= form_tag(drink_search_path, :method => "get", :id => "searchByDrink", :class => "drinkInputForm", :autocomplete => :off) do %>
                    <input type="text" placeholder="Search by drink name" class="biginput" name="searchBarDrink" id="autocompleteDrink" style="color:black" required/>
                    <%= submit_tag('Search', :class => 'submitButton', :id => 'drinkSubmitButton') %>
                  <% end %>
              </li>
              <li>
                <a class="active"><%= link_to "Get Liquor", liquorsearch_path, :method => 'get'%></a>
              </li>
            </ul><!-- /.navbar-collapse -->
      </div>  <!-- /.container-fluid -->
  </div>
</nav>
    <p>
       <%= flash[:success] unless flash[:success].blank? %>
       <%= flash[:error] unless flash[:error].blank? %>
     </p>
     <% flash.each do |name, msg| %>
       <%= content_tag :div, msg, :id => "flash_#{name}" %>
     <% end %>
</body>
  <%= yield %>
</html>